apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog-web.fullname" . }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
